language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install numexpr cython
install:
  - python setup.py develop
script:
  - python -m unittest discover
